[package]
name = "cli_ed25519_signer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.7", features = ["derive"] }
ed25519-dalek = "1.0.1"
rand = "0.7"
hex = "0.4.3"
